name: 'PR Title Check'
on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: PR Title Verify
        uses: satvik-s/pr-title-check
        with:
          pattern: '^(fix|feat|perf)'